import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ContextProvider from '@/components/context'
import Navbar from '@/components/navbar/navbar'
import NextTopLoader from 'nextjs-toploader'
import { ThemeProvider } from '@/providers/theme-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <NextTopLoader />
          <ThemeProvider
            attribute='class'
            enableSystem
          >
            <Navbar />
            <div className='container'>
              {children}
            </div>
          </ThemeProvider>
        </ContextProvider>
      </body>
    </html>
  )
}
